apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: kietph2110/myapp:09545fe215bd1e70d14225b8b270d09433009bce
        ports:
        - containerPort: 3000
